

export interface Country {
  name: string;
  code: string;
  provinces: string[];
}

// Data for all 10 ASEAN countries.
export const countries: Country[] = [
    {
        name: 'Brunei',
        code: 'BN',
        provinces: ['Belait', 'Brunei-Muara', 'Temburong', 'Tutong'],
    },
    {
        name: 'Cambodia',
        code: 'KH',
        provinces: [
          'Banteay Meanchey', 'Battambang', 'Kampong Cham', 'Kampong Chhnang', 'Kampong Speu',
          'Kampong Thom', 'Kampot', 'Kandal', 'Koh Kong', 'Kratié', 'Mondulkiri',
          'Phnom Penh', 'Preah Vihear', 'Prey Veng', 'Pursat', 'Ratanakiri', 'Siem Reap',
          'Sihanoukville (Preah Sihanouk)', 'Stung Treng', 'Svay Rieng', 'Takéo',
          'Oddar Meanchey', 'Kep', 'Pailin', 'Tboung Khmum',
        ],
    },
    {
        name: 'Indonesia',
        code: 'ID',
        provinces: [
            'Aceh', 'Bali', 'Banten', 'Bengkulu', 'Gorontalo', 'Jakarta', 'Jambi', 'West Java',
            'Central Java', 'East Java', 'West Kalimantan', 'South Kalimantan', 'Central Kalimantan',
            'East Kalimantan', 'North Kalimantan', 'Bangka Belitung Islands', 'Riau Islands', 'Lampung',
            'Maluku', 'North Maluku', 'West Nusa Tenggara', 'East Nusa Tenggara', 'Papua', 'West Papua',
            'Riau', 'West Sulawesi', 'South Sulawesi', 'Central Sulawesi', 'Southeast Sulawesi',
            'North Sulawesi', 'West Sumatra', 'South Sumatra', 'North Sumatra', 'Yogyakarta'
        ],
    },
    {
        name: 'Laos',
        code: 'LA',
        provinces: [
            'Attapeu', 'Bokeo', 'Bolikhamsai', 'Champasak', 'Houaphanh', 'Khammouane', 'Luang Namtha',
            'Luang Prabang', 'Oudomxay', 'Phongsaly', 'Salavan', 'Savannakhet', 'Vientiane Province',
            'Vientiane Prefecture', 'Sainyabuli', 'Sekong', 'Xiangkhouang', 'Xaisomboun'
        ],
    },
    {
        name: 'Malaysia',
        code: 'MY',
        provinces: [
            'Johor', 'Kedah', 'Kelantan', 'Malacca', 'Negeri Sembilan', 'Pahang', 'Penang', 'Perak',
            'Perlis', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu', 'Kuala Lumpur', 'Labuan', 'Putrajaya'
        ],
    },
    {
        name: 'Myanmar',
        code: 'MM',
        provinces: [
            'Ayeyarwady', 'Bago', 'Chin', 'Kachin', 'Kayah', 'Kayin', 'Magway', 'Mandalay', 'Mon',
            'Rakhine', 'Sagaing', 'Shan', 'Tanintharyi', 'Yangon', 'Naypyidaw Union Territory'
        ],
    },
    {
        name: 'Philippines',
        code: 'PH',
        provinces: [
            'Abra', 'Agusan del Norte', 'Agusan del Sur', 'Aklan', 'Albay', 'Antique', 'Apayao',
            'Aurora', 'Basilan', 'Bataan', 'Batanes', 'Batangas', 'Benguet', 'Biliran', 'Bohol',
            'Bukidnon', 'Bulacan', 'Cagayan', 'Camarines Norte', 'Camarines Sur', 'Camiguin',
            'Capiz', 'Catanduanes', 'Cavite', 'Cebu', 'Cotabato', 'Davao de Oro', 'Davao del Norte',
            'Davao del Sur', 'Davao Occidental', 'Davao Oriental', 'Dinagat Islands', 'Eastern Samar',
            'Guimaras', 'Ifugao', 'Ilocos Norte', 'Ilocos Sur', 'Iloilo', 'Isabela', 'Kalinga',
            'La Union', 'Laguna', 'Lanao del Norte', 'Lanao del Sur', 'Leyte', 'Maguindanao',
            'Marinduque', 'Masbate', 'Metro Manila', 'Misamis Occidental', 'Misamis Oriental',
            'Mountain Province', 'Negros Occidental', 'Negros Oriental', 'Northern Samar', 'Nueva Ecija',
            'Nueva Vizcaya', 'Occidental Mindoro', 'Oriental Mindoro', 'Palawan', 'Pampanga', 'Pangasinan',
            'Quezon', 'Quirino', 'Rizal', 'Romblon', 'Samar', 'Sarangani', 'Siquijor', 'Sorsogon',
            'South Cotabato', 'Southern Leyte', 'Sultan Kudarat', 'Sulu', 'Surigao del Norte',
            'Surigao del Sur', 'Tarlac', 'Tawi-Tawi', 'Zambales', 'Zamboanga del Norte',
            'Zamboanga del Sur', 'Zamboanga Sibugay'
        ],
    },
    {
        name: 'Singapore',
        code: 'SG',
        provinces: [
            'Central Region', 'East Region', 'North Region', 'North-East Region', 'West Region'
        ],
    },
    {
        name: 'Thailand',
        code: 'TH',
        provinces: [
            'Amnat Charoen', 'Ang Thong', 'Bangkok', 'Bueng Kan', 'Buri Ram', 'Chachoengsao', 'Chai Nat',
            'Chaiyaphum', 'Chanthaburi', 'Chiang Mai', 'Chiang Rai', 'Chon Buri', 'Chumphon', 'Kalasin',
            'Kamphaeng Phet', 'Kanchanaburi', 'Khon Kaen', 'Krabi', 'Lampang', 'Lamphun', 'Loei',
            'Lopburi', 'Mae Hong Son', 'Maha Sarakham', 'Mukdahan', 'Nakhon Nayok', 'Nakhon Pathom',
            'Nakhon Phanom', 'Nakhon Ratchasima', 'Nakhon Sawan', 'Nakhon Si Thammarat', 'Nan',
            'Narathiwat', 'Nong Bua Lam Phu', 'Nong Khai', 'Nonthaburi', 'Pathum Thani', 'Pattani',
            'Phang Nga', 'Phatthalung', 'Phayao', 'Phetchabun', 'Phetchaburi', 'Phichit', 'Phitsanulok',
            'Phra Nakhon Si Ayutthaya', 'Phrae', 'Phuket', 'Prachinburi', 'Prachuap Khiri Khan', 'Ranong',
            'Ratchaburi', 'Rayong', 'Roi Et', 'Sa Kaeo', 'Sakon Nakhon', 'Samut Prakan', 'Samut Sakhon',
            'Samut Songkhram', 'Saraburi', 'Satun', 'Sing Buri', 'Sisaket', 'Songkhla', 'Sukhothai',
            'Suphan Buri', 'Surat Thani', 'Surin', 'Tak', 'Trang', 'Trat', 'Ubon Ratchathani',
            'Udon Thani', 'Uthai Thani', 'Uttaradit', 'Yala', 'Yasothon'
        ],
    },
    {
        name: 'Vietnam',
        code: 'VN',
        provinces: [
            'An Giang', 'Ba Ria-Vung Tau', 'Bac Giang', 'Bac Kan', 'Bac Lieu', 'Bac Ninh', 'Ben Tre',
            'Binh Dinh', 'Binh Duong', 'Binh Phuoc', 'Binh Thuan', 'Ca Mau', 'Can Tho', 'Cao Bang',
            'Da Nang', 'Dak Lak', 'Dak Nong', 'Dien Bien', 'Dong Nai', 'Dong Thap', 'Gia Lai', 'Ha Giang',
            'Ha Nam', 'Ha Noi', 'Ha Tinh', 'Hai Duong', 'Hai Phong', 'Hau Giang', 'Hoa Binh', 'Ho Chi Minh City',
            'Hung Yen', 'Khanh Hoa', 'Kien Giang', 'Kon Tum', 'Lai Chau', 'Lam Dong', 'Lang Son', 'Lao Cai',
            'Long An', 'Nam Dinh', 'Nghe An', 'Ninh Binh', 'Ninh Thuan', 'Phu Tho', 'Phu Yen', 'Quang Binh',
            'Quang Nam', 'Quang Ngai', 'Quang Ninh', 'Quang Tri', 'Soc Trang', 'Son La', 'Tay Ninh',
            'Thai Binh', 'Thai Nguyen', 'Thanh Hoa', 'Thua Thien Hue', 'Tien Giang', 'Tra Vinh',
            'Tuyen Quang', 'Vinh Long', 'Vinh Phuc', 'Yen Bai'
        ],
    },
];

export interface LightweightCountry {
  name: string;
  code: string;
  phone: string;
  region: 'Asia' | 'Europe' | 'Africa' | 'North America' | 'South America' | 'Oceania' | 'Antarctica';
}

export const lightweightCountries: LightweightCountry[] = [
  { name: 'Afghanistan', code: 'AF', phone: '93', region: 'Asia' },
  { name: 'Albania', code: 'AL', phone: '355', region: 'Europe' },
  { name: 'Algeria', code: 'DZ', phone: '213', region: 'Africa' },
  { name: 'American Samoa', code: 'AS', phone: '1684', region: 'Oceania' },
  { name: 'Andorra', code: 'AD', phone: '376', region: 'Europe' },
  { name: 'Angola', code: 'AO', phone: '244', region: 'Africa' },
  { name: 'Anguilla', code: 'AI', phone: '1264', region: 'North America' },
  { name: 'Antarctica', code: 'AQ', phone: '672', region: 'Antarctica' },
  { name: 'Antigua and Barbuda', code: 'AG', phone: '1268', region: 'North America' },
  { name: 'Argentina', code: 'AR', phone: '54', region: 'South America' },
  { name: 'Armenia', code: 'AM', phone: '374', region: 'Asia' },
  { name: 'Aruba', code: 'AW', phone: '297', region: 'North America' },
  { name: 'Australia', code: 'AU', phone: '61', region: 'Oceania' },
  { name: 'Austria', code: 'AT', phone: '43', region: 'Europe' },
  { name: 'Azerbaijan', code: 'AZ', phone: '994', region: 'Asia' },
  { name: 'Bahamas', code: 'BS', phone: '1242', region: 'North America' },
  { name: 'Bahrain', code: 'BH', phone: '973', region: 'Asia' },
  { name: 'Bangladesh', code: 'BD', phone: '880', region: 'Asia' },
  { name: 'Barbados', code: 'BB', phone: '1246', region: 'North America' },
  { name: 'Belarus', code: 'BY', phone: '375', region: 'Europe' },
  { name: 'Belgium', code: 'BE', phone: '32', region: 'Europe' },
  { name: 'Belize', code: 'BZ', phone: '501', region: 'North America' },
  { name: 'Benin', code: 'BJ', phone: '229', region: 'Africa' },
  { name: 'Bermuda', code: 'BM', phone: '1441', region: 'North America' },
  { name: 'Bhutan', code: 'BT', phone: '975', region: 'Asia' },
  { name: 'Bolivia', code: 'BO', phone: '591', region: 'South America' },
  { name: 'Bosnia and Herzegovina', code: 'BA', phone: '387', region: 'Europe' },
  { name: 'Botswana', code: 'BW', phone: '267', region: 'Africa' },
  { name: 'Brazil', code: 'BR', phone: '55', region: 'South America' },
  { name: 'British Indian Ocean Territory', code: 'IO', phone: '246', region: 'Asia' },
  { name: 'British Virgin Islands', code: 'VG', phone: '1284', region: 'North America' },
  { name: 'Brunei', code: 'BN', phone: '673', region: 'Asia' },
  { name: 'Bulgaria', code: 'BG', phone: '359', region: 'Europe' },
  { name: 'Burkina Faso', code: 'BF', phone: '226', region: 'Africa' },
  { name: 'Burundi', code: 'BI', phone: '257', region: 'Africa' },
  { name: 'Cambodia', code: 'KH', phone: '855', region: 'Asia' },
  { name: 'Cameroon', code: 'CM', phone: '237', region: 'Africa' },
  { name: 'Canada', code: 'CA', phone: '1', region: 'North America' },
  { name: 'Cape Verde', code: 'CV', phone: '238', region: 'Africa' },
  { name: 'Cayman Islands', code: 'KY', phone: '1345', region: 'North America' },
  { name: 'Central African Republic', code: 'CF', phone: '236', region: 'Africa' },
  { name: 'Chad', code: 'TD', phone: '235', region: 'Africa' },
  { name: 'Chile', code: 'CL', phone: '56', region: 'South America' },
  { name: 'China', code: 'CN', phone: '86', region: 'Asia' },
  { name: 'Christmas Island', code: 'CX', phone: '61', region: 'Asia' },
  { name: 'Cocos [Keeling] Islands', code: 'CC', phone: '61', region: 'Asia' },
  { name: 'Colombia', code: 'CO', phone: '57', region: 'South America' },
  { name: 'Comoros', code: 'KM', phone: '269', region: 'Africa' },
  { name: 'Cook Islands', code: 'CK', phone: '682', region: 'Oceania' },
  { name: 'Costa Rica', code: 'CR', phone: '506', region: 'North America' },
  { name: 'Croatia', code: 'HR', phone: '385', region: 'Europe' },
  { name: 'Cuba', code: 'CU', phone: '53', region: 'North America' },
  { name: 'Curacao', code: 'CW', phone: '5999', region: 'North America' },
  { name: 'Cyprus', code: 'CY', phone: '357', region: 'Europe' },
  { name: 'Czech Republic', code: 'CZ', phone: '420', region: 'Europe' },
  { name: 'Democratic Republic of the Congo', code: 'CD', phone: '243', region: 'Africa' },
  { name: 'Denmark', code: 'DK', phone: '45', region: 'Europe' },
  { name: 'Djibouti', code: 'DJ', phone: '253', region: 'Africa' },
  { name: 'Dominica', code: 'DM', phone: '1767', region: 'North America' },
  { name: 'Dominican Republic', code: 'DO', phone: '1809', region: 'North America' },
  { name: 'East Timor', code: 'TL', phone: '670', region: 'Asia' },
  { name: 'Ecuador', code: 'EC', phone: '593', region: 'South America' },
  { name: 'Egypt', code: 'EG', phone: '20', region: 'Africa' },
  { name: 'El Salvador', code: 'SV', phone: '503', region: 'North America' },
  { name: 'Equatorial Guinea', code: 'GQ', phone: '240', region: 'Africa' },
  { name: 'Eritrea', code: 'ER', phone: '291', region: 'Africa' },
  { name: 'Estonia', code: 'EE', phone: '372', region: 'Europe' },
  { name: 'Ethiopia', code: 'ET', phone: '251', region: 'Africa' },
  { name: 'Falkland Islands', code: 'FK', phone: '500', region: 'South America' },
  { name: 'Faroe Islands', code: 'FO', phone: '298', region: 'Europe' },
  { name: 'Fiji', code: 'FJ', phone: '679', region: 'Oceania' },
  { name: 'Finland', code: 'FI', phone: '358', region: 'Europe' },
  { name: 'France', code: 'FR', phone: '33', region: 'Europe' },
  { name: 'French Guiana', code: 'GF', phone: '594', region: 'South America' },
  { name: 'French Polynesia', code: 'PF', phone: '689', region: 'Oceania' },
  { name: 'Gabon', code: 'GA', phone: '241', region: 'Africa' },
  { name: 'Gambia', code: 'GM', phone: '220', region: 'Africa' },
  { name: 'Georgia', code: 'GE', phone: '995', region: 'Asia' },
  { name: 'Germany', code: 'DE', phone: '49', region: 'Europe' },
  { name: 'Ghana', code: 'GH', phone: '233', region: 'Africa' },
  { name: 'Gibraltar', code: 'GI', phone: '350', region: 'Europe' },
  { name: 'Greece', code: 'GR', phone: '30', region: 'Europe' },
  { name: 'Greenland', code: 'GL', phone: '299', region: 'North America' },
  { name: 'Grenada', code: 'GD', phone: '1473', region: 'North America' },
  { name: 'Guadeloupe', code: 'GP', phone: '590', region: 'North America' },
  { name: 'Guam', code: 'GU', phone: '1671', region: 'Oceania' },
  { name: 'Guatemala', code: 'GT', phone: '502', region: 'North America' },
  { name: 'Guernsey', code: 'GG', phone: '44', region: 'Europe' },
  { name: 'Guinea', code: 'GN', phone: '224', region: 'Africa' },
  { name: 'Guinea-Bissau', code: 'GW', phone: '245', region: 'Africa' },
  { name: 'Guyana', code: 'GY', phone: '592', region: 'South America' },
  { name: 'Haiti', code: 'HT', phone: '509', region: 'North America' },
  { name: 'Honduras', code: 'HN', phone: '504', region: 'North America' },
  { name: 'Hong Kong', code: 'HK', phone: '852', region: 'Asia' },
  { name: 'Hungary', code: 'HU', phone: '36', region: 'Europe' },
  { name: 'Iceland', code: 'IS', phone: '354', region: 'Europe' },
  { name: 'India', code: 'IN', phone: '91', region: 'Asia' },
  { name: 'Iran', code: 'IR', phone: '98', region: 'Asia' },
  { name: 'Iraq', code: 'IQ', phone: '964', region: 'Asia' },
  { name: 'Ireland', code: 'IE', phone: '353', region: 'Europe' },
  { name: 'Isle of Man', code: 'IM', phone: '44', region: 'Europe' },
  { name: 'Israel', code: 'IL', phone: '972', region: 'Asia' },
  { name: 'Italy', code: 'IT', phone: '39', region: 'Europe' },
  { name: 'Ivory Coast', code: 'CI', phone: '225', region: 'Africa' },
  { name: 'Jamaica', code: 'JM', phone: '1876', region: 'North America' },
  { name: 'Japan', code: 'JP', phone: '81', region: 'Asia' },
  { name: 'Jersey', code: 'JE', phone: '44', region: 'Europe' },
  { name: 'Jordan', code: 'JO', phone: '962', region: 'Asia' },
  { name: 'Kazakhstan', code: 'KZ', phone: '7', region: 'Asia' },
  { name: 'Kenya', code: 'KE', phone: '254', region: 'Africa' },
  { name: 'Kiribati', code: 'KI', phone: '686', region: 'Oceania' },
  { name: 'Kosovo', code: 'XK', phone: '383', region: 'Europe' },
  { name: 'Kuwait', code: 'KW', phone: '965', region: 'Asia' },
  { name: 'Kyrgyzstan', code: 'KG', phone: '996', region: 'Asia' },
  { name: 'Laos', code: 'LA', phone: '856', region: 'Asia' },
  { name: 'Latvia', code: 'LV', phone: '371', region: 'Europe' },
  { name: 'Lebanon', code: 'LB', phone: '961', region: 'Asia' },
  { name: 'Lesotho', code: 'LS', phone: '266', region: 'Africa' },
  { name: 'Liberia', code: 'LR', phone: '231', region: 'Africa' },
  { name: 'Libya', code: 'LY', phone: '218', region: 'Africa' },
  { name: 'Liechtenstein', code: 'LI', phone: '423', region: 'Europe' },
  { name: 'Lithuania', code: 'LT', phone: '370', region: 'Europe' },
  { name: 'Luxembourg', code: 'LU', phone: '352', region: 'Europe' },
  { name: 'Macao', code: 'MO', phone: '853', region: 'Asia' },
  { name: 'Macedonia', code: 'MK', phone: '389', region: 'Europe' },
  { name: 'Madagascar', code: 'MG', phone: '261', region: 'Africa' },
  { name: 'Malawi', code: 'MW', phone: '265', region: 'Africa' },
  { name: 'Malaysia', code: 'MY', phone: '60', region: 'Asia' },
  { name: 'Maldives', code: 'MV', phone: '960', region: 'Asia' },
  { name: 'Mali', code: 'ML', phone: '223', region: 'Africa' },
  { name: 'Malta', code: 'MT', phone: '356', region: 'Europe' },
  { name: 'Marshall Islands', code: 'MH', phone: '692', region: 'Oceania' },
  { name: 'Martinique', code: 'MQ', phone: '596', region: 'North America' },
  { name: 'Mauritania', code: 'MR', phone: '222', region: 'Africa' },
  { name: 'Mauritius', code: 'MU', phone: '230', region: 'Africa' },
  { name: 'Mayotte', code: 'YT', phone: '262', region: 'Africa' },
  { name: 'Mexico', code: 'MX', phone: '52', region: 'North America' },
  { name: 'Micronesia', code: 'FM', phone: '691', region: 'Oceania' },
  { name: 'Moldova', code: 'MD', phone: '373', region: 'Europe' },
  { name: 'Monaco', code: 'MC', phone: '377', region: 'Europe' },
  { name: 'Mongolia', code: 'MN', phone: '976', region: 'Asia' },
  { name: 'Montenegro', code: 'ME', phone: '382', region: 'Europe' },
  { name: 'Montserrat', code: 'MS', phone: '1664', region: 'North America' },
  { name: 'Morocco', code: 'MA', phone: '212', region: 'Africa' },
  { name: 'Mozambique', code: 'MZ', phone: '258', region: 'Africa' },
  { name: 'Myanmar [Burma]', code: 'MM', phone: '95', region: 'Asia' },
  { name: 'Namibia', code: 'NA', phone: '264', region: 'Africa' },
  { name: 'Nauru', code: 'NR', phone: '674', region: 'Oceania' },
  { name: 'Nepal', code: 'NP', phone: '977', region: 'Asia' },
  { name: 'Netherlands', code: 'NL', phone: '31', region: 'Europe' },
  { name: 'New Caledonia', code: 'NC', phone: '687', region: 'Oceania' },
  { name: 'New Zealand', code: 'NZ', phone: '64', region: 'Oceania' },
  { name: 'Nicaragua', code: 'NI', phone: '505', region: 'North America' },
  { name: 'Niger', code: 'NE', phone: '227', region: 'Africa' },
  { name: 'Nigeria', code: 'NG', phone: '234', region: 'Africa' },
  { name: 'Niue', code: 'NU', phone: '683', region: 'Oceania' },
  { name: 'Norfolk Island', code: 'NF', phone: '672', region: 'Oceania' },
  { name: 'North Korea', code: 'KP', phone: '850', region: 'Asia' },
  { name: 'Northern Mariana Islands', code: 'MP', phone: '1670', region: 'Oceania' },
  { name: 'Norway', code: 'NO', phone: '47', region: 'Europe' },
  { name: 'Oman', code: 'OM', phone: '968', region: 'Asia' },
  { name: 'Pakistan', code: 'PK', phone: '92', region: 'Asia' },
  { name: 'Palau', code: 'PW', phone: '680', region: 'Oceania' },
  { name: 'Palestine', code: 'PS', phone: '970', region: 'Asia' },
  { name: 'Panama', code: 'PA', phone: '507', region: 'North America' },
  { name: 'Papua New Guinea', code: 'PG', phone: '675', region: 'Oceania' },
  { name: 'Paraguay', code: 'PY', phone: '595', region: 'South America' },
  { name: 'Peru', code: 'PE', phone: '51', region: 'South America' },
  { name: 'Philippines', code: 'PH', phone: '63', region: 'Asia' },
  { name: 'Pitcairn Islands', code: 'PN', phone: '64', region: 'Oceania' },
  { name: 'Poland', code: 'PL', phone: '48', region: 'Europe' },
  { name: 'Portugal', code: 'PT', phone: '351', region: 'Europe' },
  { name: 'Puerto Rico', code: 'PR', phone: '1787', region: 'North America' },
  { name: 'Qatar', code: 'QA', phone: '974', region: 'Asia' },
  { name: 'Republic of the Congo', code: 'CG', phone: '242', region: 'Africa' },
  { name: 'Réunion', code: 'RE', phone: '262', region: 'Africa' },
  { name: 'Romania', code: 'RO', phone: '40', region: 'Europe' },
  { name: 'Russia', code: 'RU', phone: '7', region: 'Europe' },
  { name: 'Rwanda', code: 'RW', phone: '250', region: 'Africa' },
  { name: 'Saint Barthélemy', code: 'BL', phone: '590', region: 'North America' },
  { name: 'Saint Helena', code: 'SH', phone: '290', region: 'Africa' },
  { name: 'Saint Kitts and Nevis', code: 'KN', phone: '1869', region: 'North America' },
  { name: 'Saint Lucia', code: 'LC', phone: '1758', region: 'North America' },
  { name: 'Saint Martin', code: 'MF', phone: '590', region: 'North America' },
  { name: 'Saint Pierre and Miquelon', code: 'PM', phone: '508', region: 'North America' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', phone: '1784', region: 'North America' },
  { name: 'Samoa', code: 'WS', phone: '685', region: 'Oceania' },
  { name: 'San Marino', code: 'SM', phone: '378', region: 'Europe' },
  { name: 'São Tomé and Príncipe', code: 'ST', phone: '239', region: 'Africa' },
  { name: 'Saudi Arabia', code: 'SA', phone: '966', region: 'Asia' },
  { name: 'Senegal', code: 'SN', phone: '221', region: 'Africa' },
  { name: 'Serbia', code: 'RS', phone: '381', region: 'Europe' },
  { name: 'Seychelles', code: 'SC', phone: '248', region: 'Africa' },
  { name: 'Sierra Leone', code: 'SL', phone: '232', region: 'Africa' },
  { name: 'Singapore', code: 'SG', phone: '65', region: 'Asia' },
  { name: 'Sint Maarten', code: 'SX', phone: '1721', region: 'North America' },
  { name: 'Slovakia', code: 'SK', phone: '421', region: 'Europe' },
  { name: 'Slovenia', code: 'SI', phone: '386', region: 'Europe' },
  { name: 'Solomon Islands', code: 'SB', phone: '677', region: 'Oceania' },
  { name: 'Somalia', code: 'SO', phone: '252', region: 'Africa' },
  { name: 'South Africa', code: 'ZA', phone: '27', region: 'Africa' },
  { name: 'South Korea', code: 'KR', phone: '82', region: 'Asia' },
  { name: 'South Sudan', code: 'SS', phone: '211', region: 'Africa' },
  { name: 'Spain', code: 'ES', phone: '34', region: 'Europe' },
  { name: 'Sri Lanka', code: 'LK', phone: '94', region: 'Asia' },
  { name: 'Sudan', code: 'SD', phone: '249', region: 'Africa' },
  { name: 'Suriname', code: 'SR', phone: '597', region: 'South America' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', phone: '4779', region: 'Europe' },
  { name: 'Swaziland', code: 'SZ', phone: '268', region: 'Africa' },
  { name: 'Sweden', code: 'SE', phone: '46', region: 'Europe' },
  { name: 'Switzerland', code: 'CH', phone: '41', region: 'Europe' },
  { name: 'Syria', code: 'SY', phone: '963', region: 'Asia' },
  { name: 'Taiwan', code: 'TW', phone: '886', region: 'Asia' },
  { name: 'Tajikistan', code: 'TJ', phone: '992', region: 'Asia' },
  { name: 'Tanzania', code: 'TZ', phone: '255', region: 'Africa' },
  { name: 'Thailand', code: 'TH', phone: '66', region: 'Asia' },
  { name: 'Togo', code: 'TG', phone: '228', region: 'Africa' },
  { name: 'Tokelau', code: 'TK', phone: '690', region: 'Oceania' },
  { name: 'Tonga', code: 'TO', phone: '676', region: 'Oceania' },
  { name: 'Trinidad and Tobago', code: 'TT', phone: '1868', region: 'North America' },
  { name: 'Tunisia', code: 'TN', phone: '216', region: 'Africa' },
  { name: 'Turkey', code: 'TR', phone: '90', region: 'Asia' },
  { name: 'Turkmenistan', code: 'TM', phone: '993', region: 'Asia' },
  { name: 'Turks and Caicos Islands', code: 'TC', phone: '1649', region: 'North America' },
  { name: 'Tuvalu', code: 'TV', phone: '688', region: 'Oceania' },
  { name: 'U.S. Virgin Islands', code: 'VI', phone: '1340', region: 'North America' },
  { name: 'Uganda', code: 'UG', phone: '256', region: 'Africa' },
  { name: 'Ukraine', code: 'UA', phone: '380', region: 'Europe' },
  { name: 'United Arab Emirates', code: 'AE', phone: '971', region: 'Asia' },
  { name: 'United Kingdom', code: 'GB', phone: '44', region: 'Europe' },
  { name: 'United States', code: 'US', phone: '1', region: 'North America' },
  { name: 'Uruguay', code: 'UY', phone: '598', region: 'South America' },
  { name: 'Uzbekistan', code: 'UZ', phone: '998', region: 'Asia' },
  { name: 'Vanuatu', code: 'VU', phone: '678', region: 'Oceania' },
  { name: 'Vatican City', code: 'VA', phone: '379', region: 'Europe' },
  { name: 'Venezuela', code: 'VE', phone: '58', region: 'South America' },
  { name: 'Vietnam', code: 'VN', phone: '84', region: 'Asia' },
  { name: 'Wallis and Futuna', code: 'WF', phone: '681', region: 'Oceania' },
  { name: 'Western Sahara', code: 'EH', phone: '212', region: 'Africa' },
  { name: 'Yemen', code: 'YE', phone: '967', region: 'Asia' },
  { name: 'Zambia', code: 'ZM', phone: '260', region: 'Africa' },
  { name: 'Zimbabwe', code: 'ZW', phone: '263', region: 'Africa' },
];
