
"use client";

// A simplified list of languages for user-facing dropdowns.
// The 'value' is a representative Azure language code used for TTS/STT.
// The 'label' is the simple name shown to the user.
export const simpleLanguages = [
    { value: 'af-ZA', label: 'Afrikaans' },
    { value: 'sq-AL', label: 'Albanian' },
    { value: 'am-ET', label: 'Amharic' },
    { value: 'ar-EG', label: 'Arabic' },
    { value: 'hy-AM', label: 'Armenian' },
    { value: 'az-AZ', label: 'Azerbaijani' },
    { value: 'eu-ES', label: 'Basque' },
    { value: 'bn-BD', label: 'Bengali' },
    { value: 'bs-BA', label: 'Bosnian' },
    { value: 'bg-BG', label: 'Bulgarian' },
    { value: 'my-MM', label: 'Burmese' },
    { value: 'ca-ES', label: 'Catalan' },
    { value: 'zh-CN', label: 'Chinese (Mandarin, Simplified)' },
    { value: 'hr-HR', label: 'Croatian' },
    { value: 'cs-CZ', label: 'Czech' },
    { value: 'da-DK', label: 'Danish' },
    { value: 'nl-NL', label: 'Dutch' },
    { value: 'en-US', label: 'English' },
    { value: 'et-EE', label: 'Estonian' },
    { value: 'fil-PH', label: 'Filipino' },
    { value: 'fi-FI', label: 'Finnish' },
    { value: 'fr-FR', label: 'French' },
    { value: 'gl-ES', label: 'Galician' },
    { value: 'ka-GE', label: 'Georgian' },
    { value: 'de-DE', label: 'German' },
    { value: 'el-GR', label: 'Greek' },
    { value: 'gu-IN', label: 'Gujarati' },
    { value: 'he-IL', label: 'Hebrew' },
    { value: 'hi-IN', label: 'Hindi' },
    { value: 'hu-HU', label: 'Hungarian' },
    { value: 'is-IS', label: 'Icelandic' },
    { value: 'id-ID', label: 'Indonesian' },
    { value: 'ga-IE', label: 'Irish' },
    { value: 'it-IT', label: 'Italian' },
    { value: 'ja-JP', label: 'Japanese' },
    { value: 'jv-ID', label: 'Javanese' },
    { value: 'kn-IN', label: 'Kannada' },
    { value: 'kk-KZ', label: 'Kazakh' },
    { value: 'km-KH', label: 'Khmer' },
    { value: 'ko-KR', label: 'Korean' },
    { value: 'lo-LA', label: 'Lao' },
    { value: 'lv-LV', label: 'Latvian' },
    { value: 'lt-LT', label: 'Lithuanian' },
    { value: 'mk-MK', label: 'Macedonian' },
    { value: 'ms-MY', label: 'Malay' },
    { value: 'ml-IN', label: 'Malayalam' },
    { value: 'mt-MT', label: 'Maltese' },
    { value: 'mr-IN', label: 'Marathi' },
    { value: 'mn-MN', label: 'Mongolian' },
    { value: 'ne-NP', label: 'Nepali' },
    { value: 'nb-NO', label: 'Norwegian Bokmål' },
    { value: 'ps-AF', label: 'Pashto' },
    { value: 'fa-IR', label: 'Persian' },
    { value: 'pl-PL', label: 'Polish' },
    { value: 'pt-BR', label: 'Portuguese' },
    { value: 'pa-IN', label: 'Punjabi' },
    { value: 'ro-RO', label: 'Romanian' },
    { value: 'ru-RU', label: 'Russian' },
    { value: 'sr-RS', label: 'Serbian' },
    { value: 'si-LK', label: 'Sinhala' },
    { value: 'sk-SK', label: 'Slovak' },
    { value: 'sl-SI', label: 'Slovenian' },
    { value: 'so-SO', label: 'Somali' },
    { value: 'es-ES', label: 'Spanish' },
    { value: 'su-ID', label: 'Sundanese' },
    { value: 'sw-KE', label: 'Swahili' },
    { value: 'sv-SE', label: 'Swedish' },
    { value: 'ta-IN', label: 'Tamil' },
    { value: 'te-IN', label: 'Telugu' },
    { value: 'th-TH', label: 'Thai' },
    { value: 'tr-TR', label: 'Turkish' },
    { value: 'uk-UA', label: 'Ukrainian' },
    { value: 'ur-PK', label: 'Urdu' },
    { value: 'uz-UZ', label: 'Uzbek' },
    { value: 'vi-VN', label: 'Vietnamese' },
    { value: 'cy-GB', label: 'Welsh' },
    { value: 'zu-ZA', label: 'Zulu' },
].sort((a, b) => a.label.localeCompare(b.label));

export type SimpleLanguageCode = typeof simpleLanguages[number]['value'];
